[metadata]
name = slc
version = 0.1.0
author = Michael Gonzales
author_email = mikiegonzales0@gmail.com
description = A python package to analyze dependency licenses.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/MichaelG922/SoftwareLicenseChecker
license = Apache-2.0
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache-2.0 License
    Operating System :: OS Independent

[options]
package_dir = 
    = src
packages = find:
include_package_data = True
python_requires = >=3.11
install_requires =
    typer

[options.extras_require]
dev =
    pytest
docs =
    sphinx
    sphinx_rtd_theme

[options.entry_points]
console_scripts =
    software-license-checker = slc.cli:app

[options.package_data]
slc = 
    core/rules/*.json